In [2]:
import pandas as pd
df = pd.read_csv("retail_store_sales.csv")
print(df.shape)

(12575, 11)

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  str
 10  Discount Applied  8376 non-null   object
dtypes: float64(3), object(1), str(7)
memory usage: 1.1+ MB
None

In [4]:
print(df.head())

  Transaction ID Customer ID       Category          Item  Price Per Unit  \
0    TXN_6867343     CUST_09     Patisserie   Item_10_PAT            18.5
1    TXN_3731986     CUST_22  Milk Products  Item_17_MILK            29.0
2    TXN_9303719     CUST_02       Butchers   Item_12_BUT            21.5
3    TXN_9458126     CUST_06      Beverages   Item_16_BEV            27.5
4    TXN_4575373     CUST_05           Food   Item_6_FOOD            12.5

   Quantity  Total Spent  Payment Method Location Transaction Date  \
0      10.0        185.0  Digital Wallet   Online       2024-04-08
1       9.0        261.0  Digital Wallet   Online       2023-07-23
2       2.0         43.0     Credit Card   Online       2022-10-05
3       9.0        247.5     Credit Card   Online       2022-05-07
4       7.0         87.5  Digital Wallet   Online       2022-10-02

  Discount Applied
0             True
1             True
2            False
3              NaN
4            False

In [5]:
print(df.describe())

       Price Per Unit      Quantity   Total Spent
count    11966.000000  11971.000000  11971.000000
mean        23.365912      5.536380    129.652577
std         10.743519      2.857883     94.750697
min          5.000000      1.000000      5.000000
25%         14.000000      3.000000     51.000000
50%         23.000000      6.000000    108.500000
75%         33.500000      8.000000    192.000000
max         41.000000     10.000000    410.000000

In [6]:
print(df.isnull())

       Transaction ID  Customer ID  Category   Item  Price Per Unit  Quantity  \
0               False        False     False  False           False     False
1               False        False     False  False           False     False
2               False        False     False  False           False     False
3               False        False     False  False           False     False
4               False        False     False  False           False     False
...               ...          ...       ...    ...             ...       ...
12570           False        False     False  False           False     False
12571           False        False     False  False           False     False
12572           False        False     False  False           False     False
12573           False        False     False  False           False     False
12574           False        False     False  False           False     False

       Total Spent  Payment Method  Location  Transaction Date  \
0            False           False     False             False
1            False           False     False             False
2            False           False     False             False
3            False           False     False             False
4            False           False     False             False
...            ...             ...       ...               ...
12570        False           False     False             False
12571        False           False     False             False
12572        False           False     False             False
12573        False           False     False             False
12574        False           False     False             False

       Discount Applied
0                 False
1                 False
2                 False
3                  True
4                 False
...                 ...
12570              True
12571             False
12572              True
12573             False
12574              True

[12575 rows x 11 columns]

In [7]:
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [8]:
print(df[df.isnull().any(axis=1)])

      Transaction ID Customer ID                       Category          Item  \
3        TXN_9458126     CUST_06                      Beverages   Item_16_BEV
5        TXN_7482416     CUST_09                     Patisserie           NaN
7        TXN_1372952     CUST_21                      Furniture           NaN
11       TXN_5422631     CUST_09                  Milk Products           NaN
14       TXN_2490363     CUST_09                  Milk Products  Item_16_MILK
...              ...         ...                            ...           ...
12564    TXN_2153066     CUST_17  Electric household essentials           NaN
12568    TXN_1096134     CUST_06                           Food   Item_4_FOOD
12570    TXN_9347481     CUST_18                     Patisserie   Item_23_PAT
12572    TXN_5306010     CUST_11                       Butchers    Item_7_BUT
12574    TXN_2407494     CUST_23                           Food   Item_9_FOOD

       Price Per Unit  Quantity  Total Spent  Payment Method  Location  \
3                27.5       9.0        247.5     Credit Card    Online
5                 NaN      10.0        200.0     Credit Card    Online
7                33.5       NaN          NaN  Digital Wallet  In-store
11                NaN       8.0         52.0  Digital Wallet  In-store
14               27.5       2.0         55.0  Digital Wallet    Online
...               ...       ...          ...             ...       ...
12564            29.0       NaN          NaN  Digital Wallet  In-store
12568             9.5       8.0         76.0  Digital Wallet  In-store
12570            38.0       4.0        152.0     Credit Card  In-store
12572            14.0      10.0        140.0            Cash    Online
12574            17.0       3.0         51.0            Cash    Online

      Transaction Date Discount Applied
3           2022-05-07              NaN
5           2023-11-30              NaN
7           2024-04-02             True
11          2025-01-12             True
14          2022-05-22              NaN
...                ...              ...
12564       2024-03-28            False
12568       2022-06-11              NaN
12570       2023-09-03              NaN
12572       2024-08-24              NaN
12574       2022-08-06              NaN

[4996 rows x 11 columns]

In [10]:
print(df[df["Price Per Unit"].isnull()]

_IncompleteInputError: incomplete input (3982998150.py, line 2)

In [11]:
import pandas as pd

df = pd.read_csv("retail_store_sales.csv")

In [12]:
print(df[df["Price Per Unit"].isnull()])

      Transaction ID Customer ID                            Category Item  \
5        TXN_7482416     CUST_09                          Patisserie  NaN
11       TXN_5422631     CUST_09                       Milk Products  NaN
17       TXN_9634894     CUST_15                       Milk Products  NaN
21       TXN_8685338     CUST_15                       Milk Products  NaN
32       TXN_1543244     CUST_20                                Food  NaN
...              ...         ...                                 ...  ...
12435    TXN_5147764     CUST_01                           Furniture  NaN
12457    TXN_1352194     CUST_17       Electric household essentials  NaN
12477    TXN_5625684     CUST_22  Computers and electric accessories  NaN
12491    TXN_7894525     CUST_23                            Butchers  NaN
12511    TXN_5715500     CUST_17                                Food  NaN

       Price Per Unit  Quantity  Total Spent  Payment Method  Location  \
5                 NaN      10.0        200.0     Credit Card    Online
11                NaN       8.0         52.0  Digital Wallet  In-store
17                NaN      10.0        275.0  Digital Wallet    Online
21                NaN       3.0        105.0     Credit Card  In-store
32                NaN       8.0        196.0     Credit Card    Online
...               ...       ...          ...             ...       ...
12435             NaN       5.0         32.5     Credit Card    Online
12457             NaN       4.0         86.0     Credit Card    Online
12477             NaN       4.0         80.0            Cash  In-store
12491             NaN       1.0         26.0     Credit Card    Online
12511             NaN       3.0        100.5  Digital Wallet    Online

      Transaction Date Discount Applied
5           2023-11-30              NaN
11          2025-01-12             True
17          2022-04-17              NaN
21          2023-10-29              NaN
32          2024-10-25             True
...                ...              ...
12435       2023-09-06             True
12457       2023-02-26              NaN
12477       2022-11-09             True
12491       2023-01-31             True
12511       2024-06-05            False

[609 rows x 11 columns]

In [13]:
print(df[df["Price Per Unit"].isnull()][
           ["Category", "Item", "Price Per Unit", "Quantity", "Total Spent"]
       ])

                                 Category Item  Price Per Unit  Quantity  \
5                              Patisserie  NaN             NaN      10.0
11                          Milk Products  NaN             NaN       8.0
17                          Milk Products  NaN             NaN      10.0
21                          Milk Products  NaN             NaN       3.0
32                                   Food  NaN             NaN       8.0
...                                   ...  ...             ...       ...
12435                           Furniture  NaN             NaN       5.0
12457       Electric household essentials  NaN             NaN       4.0
12477  Computers and electric accessories  NaN             NaN       4.0
12491                            Butchers  NaN             NaN       1.0
12511                                Food  NaN             NaN       3.0

       Total Spent
5            200.0
11            52.0
17           275.0
21           105.0
32           196.0
...            ...
12435         32.5
12457         86.0
12477         80.0
12491         26.0
12511        100.5

[609 rows x 5 columns]

In [14]:
df.head(20)

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
0,TXN_6867343,CUST_09,Patisserie,Item_10_PAT,18.5,10.0,185.0,Digital Wallet,Online,2024-04-08,True
1,TXN_3731986,CUST_22,Milk Products,Item_17_MILK,29.0,9.0,261.0,Digital Wallet,Online,2023-07-23,True
2,TXN_9303719,CUST_02,Butchers,Item_12_BUT,21.5,2.0,43.0,Credit Card,Online,2022-10-05,False
3,TXN_9458126,CUST_06,Beverages,Item_16_BEV,27.5,9.0,247.5,Credit Card,Online,2022-05-07,NaN
4,TXN_4575373,CUST_05,Food,Item_6_FOOD,12.5,7.0,87.5,Digital Wallet,Online,2022-10-02,False
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
6,TXN_3652209,CUST_07,Food,Item_1_FOOD,5.0,8.0,40.0,Credit Card,In-store,2023-06-10,True
7,TXN_1372952,CUST_21,Furniture,NaN,33.5,NaN,NaN,Digital Wallet,In-store,2024-04-02,True
8,TXN_9728486,CUST_23,Furniture,Item_16_FUR,27.5,1.0,27.5,Credit Card,In-store,2023-04-26,False
9,TXN_2722661,CUST_25,Butchers,Item_22_BUT,36.5,3.0,109.5,Cash,Online,2024-03-14,False
10,TXN_8776416,CUST_22,Butchers,Item_3_BUT,8.0,9.0,72.0,Cash,In-store,2024-12-14,True
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
12,TXN_5874772,CUST_23,Food,Item_2_FOOD,6.5,7.0,45.5,Cash,Online,2023-09-09,True
13,TXN_4413070,CUST_14,Patisserie,Item_24_PAT,39.5,6.0,237.0,Digital Wallet,In-store,2022-05-20,False
14,TXN_2490363,CUST_09,Milk Products,Item_16_MILK,27.5,2.0,55.0,Digital Wallet,Online,2022-05-22,NaN
15,TXN_1809665,CUST_14,Beverages,NaN,24.5,NaN,NaN,Credit Card,In-store,2022-05-11,NaN
16,TXN_7563311,CUST_23,Patisserie,Item_17_PAT,29.0,8.0,232.0,Cash,Online,2024-11-16,True
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
18,TXN_4396807,CUST_17,Electric household essentials,Item_13_EHE,23.0,1.0,23.0,Digital Wallet,In-store,2022-02-07,False
19,TXN_4206593,CUST_01,Furniture,NaN,35.0,NaN,NaN,Digital Wallet,Online,2025-01-13,False

In [15]:
total_price_per_unit = df["Price Per Unit"] * df["Quantity"]
print(total_price_per_unit.head(20))

0     185.0
1     261.0
2      43.0
3     247.5
4      87.5
5       NaN
6      40.0
7       NaN
8      27.5
9     109.5
10     72.0
11      NaN
12     45.5
13    237.0
14     55.0
15      NaN
16    232.0
17      NaN
18     23.0
19      NaN
dtype: float64

In [16]:
df[df["Price Per Unit"].isnull()]

,Transaction ID,Customer ID,Category,Item,Price Per Unit,Quantity,Total Spent,Payment Method,Location,Transaction Date,Discount Applied
5,TXN_7482416,CUST_09,Patisserie,NaN,NaN,10.0,200.0,Credit Card,Online,2023-11-30,NaN
11,TXN_5422631,CUST_09,Milk Products,NaN,NaN,8.0,52.0,Digital Wallet,In-store,2025-01-12,True
17,TXN_9634894,CUST_15,Milk Products,NaN,NaN,10.0,275.0,Digital Wallet,Online,2022-04-17,NaN
21,TXN_8685338,CUST_15,Milk Products,NaN,NaN,3.0,105.0,Credit Card,In-store,2023-10-29,NaN
32,TXN_1543244,CUST_20,Food,NaN,NaN,8.0,196.0,Credit Card,Online,2024-10-25,True
...,...,...,...,...,...,...,...,...,...,...,...
12435,TXN_5147764,CUST_01,Furniture,NaN,NaN,5.0,32.5,Credit Card,Online,2023-09-06,True
12457,TXN_1352194,CUST_17,Electric household essentials,NaN,NaN,4.0,86.0,Credit Card,Online,2023-02-26,NaN
12477,TXN_5625684,CUST_22,Computers and electric accessories,NaN,NaN,4.0,80.0,Cash,In-store,2022-11-09,True
12491,TXN_7894525,CUST_23,Butchers,NaN,NaN,1.0,26.0,Credit Card,Online,2023-01-31,True
12511,TXN_5715500,CUST_17,Food,NaN,NaN,3.0,100.5,Digital Wallet,Online,2024-06-05,False

In [17]:
missing_price = df[df["Price Per Unit"].isnull()]

print(
    missing_price[["Quantity", "Total Spent"]].isnull().sum()
)

Quantity       0
Total Spent    0
dtype: int64

In [18]:
missing_price["Price per unit"] = (missing_price["Total Spent"] / missing_price["Quantity"])

In [19]:
print(missing_price[[
    "Quantity",
    "Total Spent",
    "Price per unit"
]].head())

    Quantity  Total Spent  Price per unit
5       10.0        200.0            20.0
11       8.0         52.0             6.5
17      10.0        275.0            27.5
21       3.0        105.0            35.0
32       8.0        196.0            24.5

In [20]:
print((missing_price["Quantity"] == 0).sum())

0

In [21]:
print((missing_price["Total Spent"] == 0).sum())

0

In [22]:
df.loc[df["Price Per Unit"].isnull(), "Price Per Unit"] = (
    df["Total Spent"] / df["Quantity"]
)

In [23]:
print(df["Price Per Unit"].isnull().sum())

0

In [24]:
df["Price Per Unit"].head(609)

0      18.5
1      29.0
2      21.5
3      27.5
4      12.5
       ...
604     9.5
605    21.5
606     9.5
607    11.0
608    15.5
Name: Price Per Unit, Length: 609, dtype: float64

In [25]:
print(df.duplicated().sum())

0

In [26]:
import pandas as pd 
import numpy as np 
df=pd.read_csv("retail_store_sales.csv")

In [27]:
print(df.duplicated().sum())

0

In [28]:
df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"])

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12575 entries, 0 to 12574
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    12575 non-null  str
 1   Customer ID       12575 non-null  str
 2   Category          12575 non-null  str
 3   Item              11362 non-null  str
 4   Price Per Unit    11966 non-null  float64
 5   Quantity          11971 non-null  float64
 6   Total Spent       11971 non-null  float64
 7   Payment Method    12575 non-null  str
 8   Location          12575 non-null  str
 9   Transaction Date  12575 non-null  datetime64[us]
 10  Discount Applied  8376 non-null   object
dtypes: datetime64[us](1), float64(3), object(1), str(6)
memory usage: 1.1+ MB

In [30]:
print(df["Transaction Date"].dtype)

datetime64[us]

In [31]:
print(df["Transaction Date"].isnull().sum())

0

In [32]:
print(df["Discount Applied"].value_counts(dropna=False))

Discount Applied
True     4219
NaN      4199
False    4157
Name: count, dtype: int64

In [33]:
df["Discount Applied"] = df["Discount Applied"].astype("boolean")

In [34]:
print(df["Discount Applied"].dtype)

boolean

In [35]:
print(df["Discount Applied"].isnull().sum())

4199

In [36]:
missing_discount = df[df["Discount Applied"].isnull()]
print(missing_discount[["Price Per Unit", "Quantity", "Total Spent"]].isnull().sum())

Price Per Unit    205
Quantity          211
Total Spent       211
dtype: int64

In [37]:
print(missing_discount[["Category", "Item", "Price Per Unit","Quantity", "Total Spent", "Discount Applied"]].head(10))

                         Category          Item  Price Per Unit  Quantity  \
3                       Beverages   Item_16_BEV            27.5       9.0
5                      Patisserie           NaN             NaN      10.0
14                  Milk Products  Item_16_MILK            27.5       2.0
15                      Beverages           NaN            24.5       NaN
17                  Milk Products           NaN             NaN      10.0
20                      Beverages    Item_7_BEV            14.0       9.0
21                  Milk Products           NaN             NaN       3.0
22  Electric household essentials    Item_4_EHE             9.5       7.0
33  Electric household essentials   Item_21_EHE            35.0       9.0
34                     Patisserie           NaN            23.0       NaN

    Total Spent  Discount Applied
3         247.5              <NA>
5         200.0              <NA>
14         55.0              <NA>
15          NaN              <NA>
17        275.0              <NA>
20        126.0              <NA>
21        105.0              <NA>
22         66.5              <NA>
33        315.0              <NA>
34          NaN              <NA>

In [38]:
print(df.groupby("Category")["Discount Applied"].agg(["count", "size"]))

                                    count  size
Category
Beverages                            1016  1567
Butchers                             1057  1568
Computers and electric accessories   1081  1558
Electric household essentials        1050  1591
Food                                 1055  1588
Furniture                            1021  1591
Milk Products                        1089  1584
Patisserie                           1007  1528

In [39]:
print(df["Payment Method"].value_counts())

Payment Method
Cash              4310
Digital Wallet    4144
Credit Card       4121
Name: count, dtype: int64

In [40]:
print(df["Payment Method"].unique())

<StringArray>
['Digital Wallet', 'Credit Card', 'Cash']
Length: 3, dtype: str

In [41]:
print(df["Location"].unique())

<StringArray>
['Online', 'In-store']
Length: 2, dtype: str

In [42]:
print(df["Category"].unique())

<StringArray>
[                        'Patisserie',                      'Milk Products',
                           'Butchers',                          'Beverages',
                               'Food',                          'Furniture',
      'Electric household essentials', 'Computers and electric accessories']
Length: 8, dtype: str

In [43]:
print(df["Item"].nunique())

200

In [44]:
print(df["Item"].unique())

<StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',            nan,  'Item_1_FOOD',  'Item_16_FUR',
  'Item_22_BUT',   'Item_3_BUT',
 ...
   'Item_3_PAT',  'Item_13_FUR',  'Item_18_PAT', 'Item_12_MILK',
 'Item_10_MILK', 'Item_16_FOOD', 'Item_19_FOOD',  'Item_14_EHE',
   'Item_3_EHE',   'Item_9_BUT']
Length: 201, dtype: str

In [45]:
import pandas as pd
df = pd.read_csv("retail_store_sales.csv")

In [46]:
print(df["Item"].unique())

<StringArray>
[ 'Item_10_PAT', 'Item_17_MILK',  'Item_12_BUT',  'Item_16_BEV',
  'Item_6_FOOD',            nan,  'Item_1_FOOD',  'Item_16_FUR',
  'Item_22_BUT',   'Item_3_BUT',
 ...
   'Item_3_PAT',  'Item_13_FUR',  'Item_18_PAT', 'Item_12_MILK',
 'Item_10_MILK', 'Item_16_FOOD', 'Item_19_FOOD',  'Item_14_EHE',
   'Item_3_EHE',   'Item_9_BUT']
Length: 201, dtype: str

In [47]:
print(df["Item"].dropna().str.strip().nunique())

200

In [48]:
print((df["Price Per Unit"] <= 0).sum())

0

In [49]:
print((df["Quantity"] <= 0).sum())

0

In [50]:
print((df["Total Spent"] <= 0).sum())

0

In [51]:
total = df["Price Per Unit"]*df["Quantity"]
mismatch=(df["Total Spent"].notnull() & total.notnull() & (df["Total Spent"] !=total))
print(mismatch.sum())

0

In [52]:
print(df["Price Per Unit"].describe())

count    11966.000000
mean        23.365912
std         10.743519
min          5.000000
25%         14.000000
50%         23.000000
75%         33.500000
max         41.000000
Name: Price Per Unit, dtype: float64

In [53]:
Q1 = df["Price Per Unit"].quantile(0.25)
Q3 = df["Price Per Unit"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df["Price Per Unit"] < lower)|(df["Price Per Unit"] > upper)]
print("Lower boundary:", lower)
print("Upper boundary:", upper)
print("Number of outliers:", len(outliers))

Lower boundary: -15.25
Upper boundary: 62.75
Number of outliers: 0

In [54]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df["Quantity"] < lower)|(df["Quantity"] > upper)]
print("Lower boundary:", lower)
print("Upper boundary:", upper)
print("Number of outliers:", len(outliers))

Lower boundary: -4.5
Upper boundary: 15.5
Number of outliers: 0

In [55]:
Q1 = df["Total Spent"].quantile(0.25)
Q3 = df["Total Spent"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df["Total Spent"] < lower)|(df["Total Spent"] > upper)]
print("Lower boundary:", lower)
print("Upper boundary:", upper)
print("Number of outliers:", len(outliers))

Lower boundary: -160.5
Upper boundary: 403.5
Number of outliers: 60

In [56]:
print(outliers[["Category", "Item", "Price Per Unit","Quantity", "Total Spent"]].
sort_values("Total Spent", ascending=False).head(10))

                           Category          Item  Price Per Unit  Quantity  \
27                        Furniture   Item_25_FUR            41.0      10.0
133                       Furniture   Item_25_FUR            41.0      10.0
339                            Food  Item_25_FOOD            41.0      10.0
869                       Beverages   Item_25_BEV            41.0      10.0
1060                      Furniture   Item_25_FUR            41.0      10.0
1088                      Beverages   Item_25_BEV            41.0      10.0
1468                       Butchers   Item_25_BUT            41.0      10.0
1505  Electric household essentials   Item_25_EHE            41.0      10.0
1568                       Butchers   Item_25_BUT            41.0      10.0
1950                      Furniture   Item_25_FUR            41.0      10.0

      Total Spent
27          410.0
133         410.0
339         410.0
869         410.0
1060        410.0
1088        410.0
1468        410.0
1505        410.0
1568        410.0
1950        410.0

In [57]:
print(outliers["Total Spent"].value_counts().sort_index())

Total Spent
410.0    60
Name: count, dtype: int64

In [58]:
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [59]:
print(df.loc[df["Price Per Unit"].isnull(),["Quantity", "Total Spent"]].head())

    Quantity  Total Spent
5       10.0        200.0
11       8.0         52.0
17      10.0        275.0
21       3.0        105.0
32       8.0        196.0

In [60]:
missing=(df["Price Per Unit"].isnull()&df["Quantity"].notnull()&df["Total Spent"].notnull())
df.loc[missing,"Price Per Unit"]=(df.loc[missing,"Total Spent"]/df.loc[missing,"Quantity"])

In [61]:
print(df["Price Per Unit"].isnull().sum())

0

In [62]:
print(df[df["Quantity"].isnull()][["Price Per Unit", "Total Spent", "Quantity"]].head())

    Price Per Unit  Total Spent  Quantity
7             33.5          NaN       NaN
15            24.5          NaN       NaN
19            35.0          NaN       NaN
25            39.5          NaN       NaN
34            23.0          NaN       NaN

In [63]:
missing_quantity = df[df["Quantity"].isnull()]
print(missing_quantity[["Category", "Item", "Price Per Unit", "Total Spent"]].head(10))

                               Category Item  Price Per Unit  Total Spent
7                             Furniture  NaN            33.5          NaN
15                            Beverages  NaN            24.5          NaN
19                            Furniture  NaN            35.0          NaN
25                            Furniture  NaN            39.5          NaN
34                           Patisserie  NaN            23.0          NaN
83                           Patisserie  NaN            15.5          NaN
112  Computers and electric accessories  NaN            20.0          NaN
114                           Beverages  NaN            39.5          NaN
118  Computers and electric accessories  NaN            27.5          NaN
138                           Furniture  NaN            35.0          NaN

In [64]:
missing_total = df[df["Total Spent"].isnull()]
print(missing_total[["Price Per Unit", "Quantity"]].isnull().sum())

Price Per Unit      0
Quantity          604
dtype: int64

In [65]:
import pandas as pd 
df=pd.read_csv("retail_store_sales.csv")

In [66]:
missing_item = df[df["Item"].isnull()]
print(missing_item[["Category","Price Per Unit","Quantity","Total Spent"]].head(10))

         Category  Price Per Unit  Quantity  Total Spent
5      Patisserie             NaN      10.0        200.0
7       Furniture            33.5       NaN          NaN
11  Milk Products             NaN       8.0         52.0
15      Beverages            24.5       NaN          NaN
17  Milk Products             NaN      10.0        275.0
19      Furniture            35.0       NaN          NaN
21  Milk Products             NaN       3.0        105.0
25      Furniture            39.5       NaN          NaN
32           Food             NaN       8.0        196.0
34     Patisserie            23.0       NaN          NaN

In [67]:
print(df.loc[df["Item"].isnull(),["Price Per Unit", "Quantity", "Total Spent"]].notnull().all(axis=1).sum())

0

In [68]:
print(df["Discount Applied"].isnull().sum())

4199

In [69]:
df.groupby("Category")["Discount Applied"].agg(["count", "size"])

                                    count  size
Category
Beverages                            1016  1567
Butchers                             1057  1568
Computers and electric accessories   1081  1558
Electric household essentials        1050  1591
Food                                 1055  1588
Furniture                            1021  1591
Milk Products                        1089  1584
Patisserie                           1007  1528

In [70]:
print(df.duplicated().sum())

0

In [71]:
total = df["Price Per Unit"] * df["Quantity"]
missing = (df["Total Spent"].notnull()&total.notnull()&(df["Total Spent"] != total))
print(missing.sum())

0

In [72]:
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit       609
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [73]:
print(df["Price Per Unit"].isnull().sum())

609

In [74]:
import pandas as pd
df = pd.read_csv("retail_store_sales.csv")
print(df.shape)

(12575, 11)

In [75]:
print(df["Quantity"].isnull().sum())

604

In [76]:
df.loc[df["Price Per Unit"].isnull(),"Price Per Unit"]=(df["Total Spent"] / df["Quantity"])

In [77]:
print(df["Price Per Unit"].isnull().sum())

0

In [78]:
print(df[df["Quantity"].isnull()][["Price Per Unit", "Total Spent"]].isnull().sum())

Price Per Unit      0
Total Spent       604
dtype: int64

In [79]:
print(df["Quantity"].isnull().sum())

604

In [80]:
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [81]:
df.to_csv("retail_store_sales_cleaned.csv", index=False)

In [82]:
print(df.shape)

(12575, 11)

In [83]:
print(df.dtypes)

Transaction ID          str
Customer ID             str
Category                str
Item                    str
Price Per Unit      float64
Quantity            float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
Discount Applied     object
dtype: object

In [84]:
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"],errors="coerce")
df["Discount Applied"] = df["Discount Applied"].astype("boolean")

In [85]:
print(df.dtypes)

Transaction ID                 str
Customer ID                    str
Category                       str
Item                           str
Price Per Unit             float64
Quantity                   float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Discount Applied           boolean
dtype: object

In [86]:
print(df["Transaction Date"].isnull().sum())

0

In [87]:
df.to_csv("retail_store_sales_cleaned.csv", index=False)

In [88]:
import os
print(os.path.exists("retail_store_sales_cleaned.csv"))

True

In [89]:
print("Rows and Columns:", df.shape)

Rows and Columns: (12575, 11)

In [90]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [91]:
print(df.isnull().sum())

Transaction ID         0
Customer ID            0
Category               0
Item                1213
Price Per Unit         0
Quantity             604
Total Spent          604
Payment Method         0
Location               0
Transaction Date       0
Discount Applied    4199
dtype: int64

In [92]:
calculated_total = df["Price Per Unit"]*df["Quantity"]
missing =(df["Total Spent"].notnull() & calculated_total.notnull()&(df["Total Spent"] != calculated_total))
print("Total mismatches:", missing.sum())

Total mismatches: 0

In [93]:
print("Price <= 0:", (df["Price Per Unit"] <= 0).sum())
print("Quantity <= 0:", (df["Quantity"] <= 0).sum())
print("Total Spent <= 0:", (df["Total Spent"] <= 0).sum())

Price <= 0: 0
Quantity <= 0: 0
Total Spent <= 0: 0